import { TeacherStudentsViewModel } from './types';

export const initialTeacherStudentsData: TeacherStudentsViewModel = {
  students: [
    {
      id: 'student-1',
      name: 'Ayşe Kaya',
      initials: 'AK',
      grade: '11. Sınıf',
      classBranch: '11-A Sayısal',
      assignedSubjects: ['Matematik', 'Fizik'],
      mathAverageNet: 33.25,
      physicsAverageNet: 10.5,
      overallAcademicStatus: 'takipte',
      topicPerformances: [
        {
          id: 'tp-1',
          subject: 'Matematik',
          topic: 'Limit ve Süreklilik',
          masteryPercentage: 54,
          solvedQuestionCount: 140,
          accuracyRate: 58,
          status: 'needs_work',
          lastPracticedDate: 'Bugün',
        },
        {
          id: 'tp-2',
          subject: 'Matematik',
          topic: 'Trigonometri',
          masteryPercentage: 88,
          solvedQuestionCount: 220,
          accuracyRate: 91,
          status: 'mastered',
          lastPracticedDate: '26 Ağustos',
        },
        {
          id: 'tp-3',
          subject: 'Fizik',
          topic: 'Optik & Kırılma',
          masteryPercentage: 48,
          solvedQuestionCount: 95,
          accuracyRate: 52,
          status: 'needs_work',
          lastPracticedDate: 'Dün',
        },
        {
          id: 'tp-4',
          subject: 'Fizik',
          topic: 'Vektörler ve Kuvvet Dengesi',
          masteryPercentage: 82,
          solvedQuestionCount: 110,
          accuracyRate: 85,
          status: 'mastered',
          lastPracticedDate: '20 Ağustos',
        },
      ],
      recentExamResults: [
        {
          id: 'er-1',
          examTitle: 'Özdebir Türkiye Geneli TYT-1',
          date: '28 Ağustos 2026',
          subject: 'Matematik',
          correctCount: 34,
          incorrectCount: 3,
          emptyCount: 3,
          net: 33.25,
          netChange: 2.5,
          incorrectTopics: ['Limit Kavramı (1 soru)', 'Kombinatorik (2 soru)'],
        },
        {
          id: 'er-2',
          examTitle: 'Töder Kurumsal AYT Denemesi-1',
          date: '21 Ağustos 2026',
          subject: 'Fizik',
          correctCount: 11,
          incorrectCount: 2,
          emptyCount: 1,
          net: 10.5,
          netChange: 1.25,
          incorrectTopics: ['Işıkta Kırılma ve Prizmalar (2 soru)'],
        },
      ],
    },
    {
      id: 'student-3',
      name: 'Zeynep Demir',
      initials: 'ZD',
      grade: '12. Sınıf',
      classBranch: '12-B Sayısal',
      assignedSubjects: ['Matematik'],
      mathAverageNet: 15.2,
      physicsAverageNet: 0,
      overallAcademicStatus: 'kritik',
      topicPerformances: [
        {
          id: 'tp-5',
          subject: 'Matematik',
          topic: 'Vektörler',
          masteryPercentage: 35,
          solvedQuestionCount: 60,
          accuracyRate: 40,
          status: 'needs_work',
          lastPracticedDate: '5 gün önce',
        },
        {
          id: 'tp-6',
          subject: 'Matematik',
          topic: 'Türev Alma Kuralları',
          masteryPercentage: 42,
          solvedQuestionCount: 75,
          accuracyRate: 46,
          status: 'needs_work',
          lastPracticedDate: '6 gün önce',
        },
      ],
      recentExamResults: [
        {
          id: 'er-3',
          examTitle: 'Bilim Akademi Deneme-2',
          date: '18 Ağustos 2026',
          subject: 'Matematik',
          correctCount: 17,
          incorrectCount: 7,
          emptyCount: 16,
          net: 15.25,
          netChange: -5.5,
          incorrectTopics: ['Vektörler', 'Türev', 'Fonksiyon Grafikleri'],
        },
      ],
    },
  ],
};
