import { StudentExamsViewModel } from './types';

export const initialStudentExamsData: StudentExamsViewModel = {
  averageNetTYT: 98.4,
  averageNetAYT: 64.2,
  targetNetTYT: 105.0,
  targetNetAYT: 72.0,
  latestExam: {
    id: 'exam-004',
    title: 'Özdebir Türkiye Geneli TYT-1',
    type: 'TYT',
    date: '28 Ağustos 2026',
    totalNet: 101.0,
    maxTotalNet: 120,
    rankInInstitution: 14,
    totalStudents: 180,
    netChange: 4.25,
    coachReviewNote: 'Türkçe ve Matematik netlerin hedef bandında. Fen kısmında Fizik Optik konusuna dikkat et.',
    focusWeakTopics: ['Optik & Kırılma', 'Mol Kavramı', 'Cümlede Anlam'],
    subjects: [
      { subjectName: 'Türkçe', correct: 36, wrong: 4, empty: 0, net: 35.0, maxNet: 40, targetNet: 36, changeFromPrevious: 1.25 },
      { subjectName: 'Temel Matematik', correct: 34, wrong: 3, empty: 3, net: 33.25, maxNet: 40, targetNet: 35, changeFromPrevious: 2.5 },
      { subjectName: 'Fen Bilimleri', correct: 17, wrong: 2, empty: 1, net: 16.5, maxNet: 20, targetNet: 18, changeFromPrevious: -0.5 },
      { subjectName: 'Sosyal Bilimler', correct: 17, wrong: 3, empty: 0, net: 16.25, maxNet: 20, targetNet: 17, changeFromPrevious: 1.0 },
    ],
  },
  exams: [
    {
      id: 'exam-004',
      title: 'Özdebir Türkiye Geneli TYT-1',
      type: 'TYT',
      date: '28 Ağustos 2026',
      totalNet: 101.0,
      maxTotalNet: 120,
      rankInInstitution: 14,
      totalStudents: 180,
      netChange: 4.25,
      coachReviewNote: 'Türkçe ve Matematik netlerin hedef bandında. Fen kısmında Fizik Optik konusuna dikkat et.',
      focusWeakTopics: ['Optik & Kırılma', 'Mol Kavramı', 'Cümlede Anlam'],
      subjects: [
        { subjectName: 'Türkçe', correct: 36, wrong: 4, empty: 0, net: 35.0, maxNet: 40, targetNet: 36, changeFromPrevious: 1.25 },
        { subjectName: 'Temel Matematik', correct: 34, wrong: 3, empty: 3, net: 33.25, maxNet: 40, targetNet: 35, changeFromPrevious: 2.5 },
        { subjectName: 'Fen Bilimleri', correct: 17, wrong: 2, empty: 1, net: 16.5, maxNet: 20, targetNet: 18, changeFromPrevious: -0.5 },
        { subjectName: 'Sosyal Bilimler', correct: 17, wrong: 3, empty: 0, net: 16.25, maxNet: 20, targetNet: 17, changeFromPrevious: 1.0 },
      ],
    },
    {
      id: 'exam-003',
      title: 'Töder Kurumsal AYT Denemesi-1',
      type: 'AYT',
      date: '21 Ağustos 2026',
      totalNet: 64.5,
      maxTotalNet: 80,
      rankInInstitution: 18,
      totalStudents: 165,
      netChange: 2.75,
      focusWeakTopics: ['Limit & Süreklilik', 'İki Boyutta Hareket'],
      subjects: [
        { subjectName: 'AYT Matematik', correct: 33, wrong: 3, empty: 4, net: 32.25, maxNet: 40, targetNet: 35, changeFromPrevious: 1.75 },
        { subjectName: 'AYT Fizik', correct: 11, wrong: 2, empty: 1, net: 10.5, maxNet: 14, targetNet: 12, changeFromPrevious: 0.5 },
        { subjectName: 'AYT Kimya', correct: 12, wrong: 1, empty: 0, net: 11.75, maxNet: 13, targetNet: 12, changeFromPrevious: 0.25 },
        { subjectName: 'AYT Biyoloji', correct: 10, wrong: 0, empty: 3, net: 10.0, maxNet: 13, targetNet: 11, changeFromPrevious: 0.25 },
      ],
    },
    {
      id: 'exam-002',
      title: 'Bilim Akademi Seviye Tespit TYT',
      type: 'TYT',
      date: '14 Ağustos 2026',
      totalNet: 96.75,
      maxTotalNet: 120,
      rankInInstitution: 22,
      totalStudents: 180,
      netChange: 3.5,
      subjects: [
        { subjectName: 'Türkçe', correct: 35, wrong: 5, empty: 0, net: 33.75, maxNet: 40 },
        { subjectName: 'Temel Matematik', correct: 32, wrong: 5, empty: 3, net: 30.75, maxNet: 40 },
        { subjectName: 'Fen Bilimleri', correct: 18, wrong: 4, empty: 0, net: 17.0, maxNet: 20 },
        { subjectName: 'Sosyal Bilimler', correct: 16, wrong: 3, empty: 1, net: 15.25, maxNet: 20 },
      ],
    },
    {
      id: 'exam-001',
      title: 'Yaz Kampı Başlangıç TYT',
      type: 'TYT',
      date: '1 Ağustos 2026',
      totalNet: 93.25,
      maxTotalNet: 120,
      rankInInstitution: 29,
      totalStudents: 175,
      netChange: 0,
      subjects: [
        { subjectName: 'Türkçe', correct: 34, wrong: 6, empty: 0, net: 32.5, maxNet: 40 },
        { subjectName: 'Temel Matematik', correct: 30, wrong: 4, empty: 6, net: 29.0, maxNet: 40 },
        { subjectName: 'Fen Bilimleri', correct: 17, wrong: 2, empty: 1, net: 16.5, maxNet: 20 },
        { subjectName: 'Sosyal Bilimler', correct: 16, wrong: 3, empty: 1, net: 15.25, maxNet: 20 },
      ],
    },
  ],
};
