import { AuthUser, UserRole } from './types';

export const DEVELOPMENT_USERS: Record<UserRole, AuthUser> = {
  student: {
    id: 'usr-student-1',
    name: 'Ayşe Kaya',
    email: 'ayse.kaya@bilimakademi.k12.tr',
    role: 'student',
    initials: 'AK',
    roleLabel: '11. Sınıf • Sayısal',
    institutionName: 'Merkez Şube',
    branchName: 'Merkez Şube',
  },
  coach: {
    id: 'usr-coach-1',
    name: 'Hasan Yılmaz',
    email: 'hasan.yilmaz@bilimakademi.k12.tr',
    role: 'coach',
    initials: 'HY',
    roleLabel: 'Kıdemli YKS Koçu',
    institutionName: 'Kadıköy Şubesi',
    branchName: 'Kadıköy Şubesi',
  },
  teacher: {
    id: 'usr-teacher-1',
    name: 'Kemal Bey',
    email: 'kemal.bey@bilimakademi.k12.tr',
    role: 'teacher',
    initials: 'KB',
    roleLabel: 'Matematik & Fizik Zümresi',
    institutionName: 'Kadıköy Şubesi',
    branchName: 'Kadıköy Şubesi',
  },
  parent: {
    id: 'usr-parent-1',
    name: 'Merve Kaya',
    email: 'merve.kaya@example.com',
    role: 'parent',
    initials: 'MK',
    roleLabel: 'Veli',
    institutionName: 'Kadıköy Şubesi',
    branchName: 'Kadıköy Şubesi',
  },
  admin: {
    id: 'usr-admin-1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet.yilmaz@bilimakademi.k12.tr',
    role: 'admin',
    initials: 'AY',
    roleLabel: 'Kurum Müdürü',
    institutionName: 'Merkez & 6 Şube',
    branchName: 'Genel Merkez',
  },
};
