import { TeacherDashboardViewModel } from './types';

export const initialTeacherDashboardData: TeacherDashboardViewModel = {
  teacherName: 'Kemal Bey',
  assignedSubjects: ['Matematik', 'Fizik'],
  totalAssignedStudents: 6,
  totalAssignedClasses: 3,
  academicGaps: [
    {
      id: 'gap-1',
      studentId: 'student-1',
      studentName: 'Ayşe Kaya',
      grade: '11. Sınıf',
      subject: 'Matematik',
      topic: 'Limit ve Süreklilik',
      detail: 'Son 2 denemede 12 yanlış — temel kavramda boşluk var',
      severity: 'critical',
      initials: 'AK',
      lastExam: '28 Eki 2026',
    },
    {
      id: 'gap-2',
      studentId: 'student-2',
      studentName: 'Mehmet Yılmaz',
      grade: '10. Sınıf',
      subject: 'Matematik',
      topic: 'Türev Uygulamaları',
      detail: 'Tekrar öneriliyor — kavram anlaşılmış ama uygulamada hata oranı yüksek',
      severity: 'warning',
      initials: 'MY',
      lastExam: '25 Eki 2026',
    },
    {
      id: 'gap-3',
      studentId: 'student-3',
      studentName: 'Zeynep Demir',
      grade: '12. Sınıf',
      subject: 'Matematik',
      topic: 'Vektörler',
      detail: 'Geçen 3 denemede sürekli yanlış — acil öncelik',
      severity: 'critical',
      initials: 'ZD',
      lastExam: '30 Eki 2026',
    },
    {
      id: 'gap-4',
      studentId: 'student-5',
      studentName: 'Burak Arslan',
      grade: '9. Sınıf',
      subject: 'Fizik',
      topic: 'Kuvvet ve Hareket',
      detail: 'Temel kavramlar eksik — fizik başlangıç konuları için ek destek önerilir',
      severity: 'warning',
      initials: 'BA',
      lastExam: '28 Eki 2026',
    },
    {
      id: 'gap-5',
      studentId: 'student-6',
      studentName: 'Selin Koç',
      grade: '12. Sınıf',
      subject: 'Fizik',
      topic: 'Optik',
      detail: 'Son deneme net: 8/12 — gelişme var, takipte kal',
      severity: 'info',
      initials: 'SK',
      lastExam: '30 Eki 2026',
    },
  ],
  studentNets: [
    { id: 'sn-1', studentId: 'student-1', name: 'Ayşe Kaya', grade: '11', mathNet: 22.4, physicsNet: null, trend: 'up', initials: 'AK' },
    { id: 'sn-2', studentId: 'student-2', name: 'Mehmet Yılmaz', grade: '10', mathNet: 18.7, physicsNet: null, trend: 'stable', initials: 'MY' },
    { id: 'sn-3', studentId: 'student-3', name: 'Zeynep Demir', grade: '12', mathNet: 15.2, physicsNet: null, trend: 'down', initials: 'ZD' },
    { id: 'sn-4', studentId: 'student-5', name: 'Burak Arslan', grade: '9', mathNet: 12.1, physicsNet: 8.3, trend: 'up', initials: 'BA' },
    { id: 'sn-5', studentId: 'student-6', name: 'Selin Koç', grade: '12', mathNet: null, physicsNet: 9.4, trend: 'up', initials: 'SK' },
    { id: 'sn-6', studentId: 'student-8', name: 'Emre Türk', grade: '11', mathNet: 19.8, physicsNet: 11.2, trend: 'stable', initials: 'ET' },
  ],
};
