import { AdminCoachesViewModel } from './types';

export const initialAdminCoachesData: AdminCoachesViewModel = {
  coaches: [
    {
      id: 'coach-1',
      name: 'Hasan Yılmaz',
      title: 'Kıdemli YKS Koçu',
      initials: 'HY',
      assignedStudentCount: 24,
      portfolioCapacity: 25,
      averageAdherencePercentage: 88,
      averageWeeklyStudyHours: 20.1,
      attentionStudentCount: 3,
      branch: 'Kadıköy',
      status: 'active',
    },
    {
      id: 'coach-2',
      name: 'Merve Aksoy',
      title: 'YKS / LGS Koçu',
      initials: 'MA',
      assignedStudentCount: 22,
      portfolioCapacity: 25,
      averageAdherencePercentage: 82,
      averageWeeklyStudyHours: 19.4,
      attentionStudentCount: 1,
      branch: 'Şişli',
      status: 'active',
    },
    {
      id: 'coach-3',
      name: 'Kemal Demir',
      title: 'Akademik Gelişim Koçu',
      initials: 'KD',
      assignedStudentCount: 19,
      portfolioCapacity: 25,
      averageAdherencePercentage: 71,
      averageWeeklyStudyHours: 17.8,
      attentionStudentCount: 4,
      branch: 'Ümraniye',
      status: 'active',
    },
    {
      id: 'coach-4',
      name: 'Seda Polat',
      title: 'YKS Koçu',
      initials: 'SP',
      assignedStudentCount: 20,
      portfolioCapacity: 25,
      averageAdherencePercentage: 79,
      averageWeeklyStudyHours: 18.6,
      attentionStudentCount: 2,
      branch: 'Kadıköy',
      status: 'active',
    },
  ],
};
