import { TeacherClassesViewModel } from './types';

export const initialTeacherClassesData: TeacherClassesViewModel = {
  classes: [
    {
      id: 'class-11a',
      name: '11-A Sayısal',
      grade: '11. Sınıf',
      branch: 'Sayısal',
      subject: 'Matematik & Fizik',
      studentCount: 22,
      averageNet: 24.8,
      attentionRequiredCount: 2,
      recentExamTitle: 'Özdebir TYT-1',
      recentExamAverageNet: 23.5,
      students: [
        {
          id: 'cs-1',
          studentId: 'student-1',
          name: 'Ayşe Kaya',
          initials: 'AK',
          mathNet: 33.25,
          physicsNet: 10.5,
          status: 'takipte',
          trend: 'up',
          weakTopic: 'Limit ve Süreklilik',
        },
        {
          id: 'cs-2',
          studentId: 'student-8',
          name: 'Emre Türk',
          initials: 'ET',
          mathNet: 19.8,
          physicsNet: 11.2,
          status: 'kritik',
          trend: 'stable',
          weakTopic: 'Optik & Kırılma',
        },
      ],
      topicMasteries: [
        { topic: 'Limit ve Süreklilik', subject: 'Matematik', masteryPercentage: 62, unmasteredStudentCount: 8 },
        { topic: 'Optik & Kırılma', subject: 'Fizik', masteryPercentage: 54, unmasteredStudentCount: 10 },
        { topic: 'Trigonometri', subject: 'Matematik', masteryPercentage: 78, unmasteredStudentCount: 5 },
        { topic: 'Vektörler', subject: 'Fizik', masteryPercentage: 85, unmasteredStudentCount: 3 },
      ],
    },
    {
      id: 'class-12b',
      name: '12-B Sayısal',
      grade: '12. Sınıf',
      branch: 'Sayısal (AYT)',
      subject: 'Matematik & Fizik',
      studentCount: 18,
      averageNet: 28.4,
      attentionRequiredCount: 2,
      recentExamTitle: 'Töder AYT-1',
      recentExamAverageNet: 27.2,
      students: [
        {
          id: 'cs-3',
          studentId: 'student-3',
          name: 'Zeynep Demir',
          initials: 'ZD',
          mathNet: 15.2,
          physicsNet: null,
          status: 'kritik',
          trend: 'down',
          weakTopic: 'Vektörler',
        },
        {
          id: 'cs-4',
          studentId: 'student-6',
          name: 'Selin Koç',
          initials: 'SK',
          mathNet: null,
          physicsNet: 9.4,
          status: 'takipte',
          trend: 'up',
          weakTopic: 'Optik',
        },
      ],
      topicMasteries: [
        { topic: 'Türev & Uygulamaları', subject: 'Matematik', masteryPercentage: 58, unmasteredStudentCount: 7 },
        { topic: 'İntegral', subject: 'Matematik', masteryPercentage: 46, unmasteredStudentCount: 9 },
        { topic: 'Elektrik & Manyetizma', subject: 'Fizik', masteryPercentage: 72, unmasteredStudentCount: 5 },
      ],
    },
    {
      id: 'class-10c',
      name: '10-C Karma',
      grade: '10. Sınıf',
      branch: 'Alan Öncesi',
      subject: 'Matematik',
      studentCount: 24,
      averageNet: 18.2,
      attentionRequiredCount: 1,
      recentExamTitle: 'Kurumsal Tarama-1',
      recentExamAverageNet: 17.5,
      students: [
        {
          id: 'cs-5',
          studentId: 'student-2',
          name: 'Mehmet Yılmaz',
          initials: 'MY',
          mathNet: 18.7,
          physicsNet: null,
          status: 'dikkat',
          trend: 'stable',
          weakTopic: 'Türev Uygulamaları',
        },
      ],
      topicMasteries: [
        { topic: 'Fonksiyonlar', subject: 'Matematik', masteryPercentage: 68, unmasteredStudentCount: 7 },
        { topic: 'Polinomlar', subject: 'Matematik', masteryPercentage: 75, unmasteredStudentCount: 6 },
        { topic: 'İkinci Dereceden Denklemler', subject: 'Matematik', masteryPercentage: 81, unmasteredStudentCount: 4 },
      ],
    },
  ],
};
