import { InstitutionOverviewViewModel } from './types';

export const initialAdminOverviewData: InstitutionOverviewViewModel = {
  institutionName: 'Bilim Akademi',
  branchCount: 6,
  kpis: [
    {
      label: 'Aktif Öğrenci',
      value: '423',
      sub: '4 şubede',
      iconType: 'users',
      color: 'bg-primary-50 text-primary-600',
    },
    {
      label: 'Aktif Koç',
      value: '18',
      sub: '3 kıdemli',
      iconType: 'coaches',
      color: 'bg-navy-50 text-navy-600',
    },
    {
      label: 'Ortalama Plan Uyumu',
      value: '%78',
      sub: '+3 puan bu ay',
      iconType: 'adherence',
      color: 'bg-success-light text-success',
    },
    {
      label: 'Haftalık Çalışma Ort.',
      value: '19.2 sa',
      sub: 'öğrenci başına',
      iconType: 'clock',
      color: 'bg-warning-light text-warning',
    },
  ],
  trendData: {
    '1m': [
      { ay: 'Eyl 26', turkce: 24.8, matematik: 18.2, sosyal: 16.4, fen: 14.9 },
      { ay: 'Eki 26', turkce: 26.1, matematik: 19.8, sosyal: 17.2, fen: 15.8 },
      { ay: 'Kas 26', turkce: 27.4, matematik: 21.3, sosyal: 17.9, fen: 16.2 },
      { ay: 'Ara 26', turkce: 28.2, matematik: 22.7, sosyal: 18.6, fen: 17.1 },
    ],
    '3m': [
      { ay: 'Ağu 26', turkce: 22.1, matematik: 15.9, sosyal: 14.3, fen: 12.7 },
      { ay: 'Eyl 26', turkce: 24.8, matematik: 18.2, sosyal: 16.4, fen: 14.9 },
      { ay: 'Eki 26', turkce: 26.1, matematik: 19.8, sosyal: 17.2, fen: 15.8 },
      { ay: 'Kas 26', turkce: 27.4, matematik: 21.3, sosyal: 17.9, fen: 16.2 },
      { ay: 'Ara 26', turkce: 28.2, matematik: 22.7, sosyal: 18.6, fen: 17.1 },
    ],
    '6m': [
      { ay: 'May 26', turkce: 19.4, matematik: 13.2, sosyal: 12.1, fen: 10.8 },
      { ay: 'Haz 26', turkce: 20.8, matematik: 14.5, sosyal: 13.0, fen: 11.9 },
      { ay: 'Tem 26', turkce: 21.2, matematik: 15.1, sosyal: 13.8, fen: 12.3 },
      { ay: 'Ağu 26', turkce: 22.1, matematik: 15.9, sosyal: 14.3, fen: 12.7 },
      { ay: 'Eyl 26', turkce: 24.8, matematik: 18.2, sosyal: 16.4, fen: 14.9 },
      { ay: 'Eki 26', turkce: 26.1, matematik: 19.8, sosyal: 17.2, fen: 15.8 },
      { ay: 'Kas 26', turkce: 27.4, matematik: 21.3, sosyal: 17.9, fen: 16.2 },
      { ay: 'Ara 26', turkce: 28.2, matematik: 22.7, sosyal: 18.6, fen: 17.1 },
    ],
  },
  attentionStats: [
    { label: 'Kritik öğrenci', value: '8', sub: '7+ gün aktivite yok' },
    { label: 'Düşük plan uyumu', value: '31', sub: '<%50 bu hafta' },
  ],
  coaches: [
    {
      id: 'coach-1',
      name: 'Hasan Yılmaz',
      initials: 'HY',
      students: 24,
      adherence: 88,
      avgStudy: 20.1,
      attention: 3,
      status: 'good',
    },
    {
      id: 'coach-2',
      name: 'Merve Aksoy',
      initials: 'MA',
      students: 22,
      adherence: 82,
      avgStudy: 19.4,
      attention: 1,
      status: 'good',
    },
    {
      id: 'coach-3',
      name: 'Kemal Demir',
      initials: 'KD',
      students: 19,
      adherence: 71,
      avgStudy: 17.8,
      attention: 4,
      status: 'attention',
    },
    {
      id: 'coach-4',
      name: 'Seda Polat',
      initials: 'SP',
      students: 20,
      adherence: 79,
      avgStudy: 18.6,
      attention: 2,
      status: 'good',
    },
  ],
};
