import { AdminStudentDirectoryViewModel } from './types';

export const initialAdminStudentsData: AdminStudentDirectoryViewModel = {
  students: [
    {
      id: 'student-1',
      name: 'Ayşe Kaya',
      initials: 'AK',
      grade: '11',
      exam: 'AYT',
      field: 'Sayısal',
      status: 'takipte',
      planAdherence: 91,
      lastActivity: 'Bugün',
      lastActivityDays: 0,
      coach: 'Hasan Yılmaz',
      branch: 'Kadıköy',
    },
    {
      id: 'student-2',
      name: 'Mehmet Yılmaz',
      initials: 'MY',
      grade: '10',
      exam: 'TYT',
      field: 'EA',
      status: 'takipte',
      planAdherence: 78,
      lastActivity: 'Dün',
      lastActivityDays: 1,
      coach: 'Merve Aksoy',
      branch: 'Şişli',
    },
    {
      id: 'student-3',
      name: 'Zeynep Demir',
      initials: 'ZD',
      grade: '12',
      exam: 'AYT',
      field: 'Sayısal',
      status: 'kritik',
      planAdherence: 34,
      lastActivity: '5 gün önce',
      lastActivityDays: 5,
      coach: 'Hasan Yılmaz',
      branch: 'Kadıköy',
    },
    {
      id: 'student-4',
      name: 'Ali Çelik',
      initials: 'AÇ',
      grade: '11',
      exam: 'AYT',
      field: 'EA',
      status: 'dikkat',
      planAdherence: 58,
      lastActivity: 'Dün',
      lastActivityDays: 1,
      coach: 'Hasan Yılmaz',
      branch: 'Ümraniye',
    },
    {
      id: 'student-5',
      name: 'Fatma Şahin',
      initials: 'FŞ',
      grade: '12',
      exam: 'AYT',
      field: 'Sözel',
      status: 'dikkat',
      planAdherence: 63,
      lastActivity: '2 gün önce',
      lastActivityDays: 2,
      coach: 'Kemal Demir',
      branch: 'Kadıköy',
    },
    {
      id: 'student-6',
      name: 'Burak Arslan',
      initials: 'BA',
      grade: '9',
      exam: 'TYT',
      field: 'Sayısal',
      status: 'takipte',
      planAdherence: 85,
      lastActivity: 'Bugün',
      lastActivityDays: 0,
      coach: 'Merve Aksoy',
      branch: 'Şişli',
    },
    {
      id: 'student-7',
      name: 'Selin Koç',
      initials: 'SK',
      grade: '12',
      exam: 'AYT',
      field: 'Dil',
      status: 'takipte',
      planAdherence: 88,
      lastActivity: 'Bugün',
      lastActivityDays: 0,
      coach: 'Kemal Demir',
      branch: 'Ümraniye',
    },
    {
      id: 'student-8',
      name: 'Emre Türk',
      initials: 'ET',
      grade: '11',
      exam: 'AYT',
      field: 'Sözel',
      status: 'kritik',
      planAdherence: 21,
      lastActivity: '8 gün önce',
      lastActivityDays: 8,
      coach: 'Hasan Yılmaz',
      branch: 'Kadıköy',
    },
    {
      id: 'student-9',
      name: 'Nur Aydın',
      initials: 'NA',
      grade: '10',
      exam: 'TYT',
      field: 'EA',
      status: 'takipte',
      planAdherence: 73,
      lastActivity: 'Dün',
      lastActivityDays: 1,
      coach: 'Merve Aksoy',
      branch: 'Şişli',
    },
    {
      id: 'student-10',
      name: 'Yusuf Öz',
      initials: 'YÖ',
      grade: '12',
      exam: 'AYT',
      field: 'Sayısal',
      status: 'dikkat',
      planAdherence: 54,
      lastActivity: '3 gün önce',
      lastActivityDays: 3,
      coach: 'Kemal Demir',
      branch: 'Ümraniye',
    },
  ],
};
