import { CoachMeetingsViewModel } from './types';

export const initialCoachMeetingsData: CoachMeetingsViewModel = {
  meetings: [
    {
      id: 'meet-1',
      studentId: 'student-1',
      studentName: 'Ayşe Kaya',
      initials: 'AK',
      grade: '11. Sınıf',
      field: 'Sayısal',
      dateStr: 'Bugün (1 Eyl)',
      timeStr: '14:30',
      durationMinutes: 30,
      type: 'Haftalık Plan Değerlendirmesi',
      locationType: 'Online Video',
      status: 'upcoming',
      notes: 'Optik ve Limit çalışmaları değerlendirilecek.',
    },
    {
      id: 'meet-2',
      studentId: 'student-4',
      studentName: 'Ali Çelik',
      initials: 'AÇ',
      grade: '11. Sınıf',
      field: 'Eşit Ağırlık',
      dateStr: 'Bugün (1 Eyl)',
      timeStr: '16:00',
      durationMinutes: 45,
      type: 'Geometri Hedef Belirleme',
      locationType: 'Yüz Yüze • Kurum',
      status: 'upcoming',
      notes: 'Üçgenler soru fasikülü ödev kontrolü.',
    },
    {
      id: 'meet-3',
      studentId: 'student-3',
      studentName: 'Zeynep Demir',
      initials: 'ZD',
      grade: '12. Sınıf',
      field: 'Sayısal',
      dateStr: 'Bugün (1 Eyl)',
      timeStr: '17:15',
      durationMinutes: 30,
      type: 'Motivasyon & Devamsızlık Takibi',
      locationType: 'Online Video',
      status: 'upcoming',
      notes: 'Son 5 günlük aksamayı telafi etme planı.',
    },
    {
      id: 'meet-4',
      studentId: 'student-8',
      studentName: 'Emre Türk',
      initials: 'ET',
      grade: '11. Sınıf',
      field: 'Sözel',
      dateStr: 'Yarın (2 Eyl)',
      timeStr: '15:00',
      durationMinutes: 30,
      type: 'Edebiyat Deneme Analizi',
      locationType: 'Online Video',
      status: 'upcoming',
    },
    {
      id: 'meet-5',
      studentId: 'student-9',
      studentName: 'Nur Aydın',
      initials: 'NA',
      grade: '10. Sınıf',
      field: 'Eşit Ağırlık',
      dateStr: '28 Ağustos 2026',
      timeStr: '11:00',
      durationMinutes: 40,
      type: 'Aylık Gelişim Raporu',
      locationType: 'Yüz Yüze • Kurum',
      status: 'completed',
    },
  ],
};
