<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EgitimPlatform.Modules.Coaching</RootNamespace>
    <AssemblyName>EgitimPlatform.Modules.Coaching</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EgitimPlatform.BuildingBlocks\EgitimPlatform.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Identity\EgitimPlatform.Modules.Identity\EgitimPlatform.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Students\EgitimPlatform.Modules.Students\EgitimPlatform.Modules.Students.csproj" />
  </ItemGroup>

</Project>
