<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EgittimPlatform.Modules.Content</RootNamespace>
    <AssemblyName>EgittimPlatform.Modules.Content</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EgittimPlatform.BuildingBlocks\EgittimPlatform.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
