import { StudentPlanViewModel } from './types';

export const initialStudentPlanData: StudentPlanViewModel = {
  planId: 'plan-2026-w36',
  title: 'YKS 2027 Sayısal Hedef Planı',
  academicGoal: 'TYT 100+ Net / AYT 70+ Net',
  coachName: 'Hasan Yılmaz',
  coachAvatarInitials: 'HY',
  currentWeek: '1. Hafta',
  dateRange: '1 - 7 Eylül 2026',
  completionRate: 72,
  totalTasks: 25,
  completedTasks: 18,
  days: [
    { dayIndex: 0, dayName: 'Pzt', dateStr: '1 Eyl', taskCount: 4, completedCount: 4 },
    { dayIndex: 1, dayName: 'Sal', dateStr: '2 Eyl', taskCount: 4, completedCount: 3, isToday: true },
    { dayIndex: 2, dayName: 'Çar', dateStr: '3 Eyl', taskCount: 3, completedCount: 3 },
    { dayIndex: 3, dayName: 'Per', dateStr: '4 Eyl', taskCount: 4, completedCount: 2 },
    { dayIndex: 4, dayName: 'Cum', dateStr: '5 Eyl', taskCount: 4, completedCount: 3 },
    { dayIndex: 5, dayName: 'Cmt', dateStr: '6 Eyl', taskCount: 3, completedCount: 2 },
    { dayIndex: 6, dayName: 'Paz', dateStr: '7 Eyl', taskCount: 3, completedCount: 1 },
  ],
  tasks: [
    {
      id: 'task-101',
      dayIndex: 1,
      subject: 'Matematik',
      topic: 'Limit ve Süreklilik — Temel Kavramlar',
      durationMinutes: 90,
      status: 'completed',
      isCoachAssigned: true,
      coachNote: 'Önceki denemedeki limit sorularının analizine dikkat et.',
      targetQuestionCount: 45,
      completedAt: '09:30',
    },
    {
      id: 'task-102',
      dayIndex: 1,
      subject: 'TYT Analizi',
      topic: 'Kasım Denemesi Matematik Çözümleri',
      durationMinutes: 45,
      status: 'in_progress',
      isCoachAssigned: true,
      coachNote: 'Yapamadığın 3 geometri sorusunu kesip defterine yapıştır.',
    },
    {
      id: 'task-103',
      dayIndex: 1,
      subject: 'Türkçe',
      topic: 'Sözcük Türleri — Pekiştirme Testi',
      durationMinutes: 60,
      status: 'pending',
      targetQuestionCount: 40,
    },
    {
      id: 'task-104',
      dayIndex: 1,
      subject: 'Felsefe',
      topic: 'Ahlak Felsefesi Kavram Haritası',
      durationMinutes: 30,
      status: 'pending',
    },
    // Other days tasks
    {
      id: 'task-201',
      dayIndex: 0,
      subject: 'Fizik',
      topic: 'Vektörler ve Bağıl Hareket',
      durationMinutes: 75,
      status: 'completed',
      isCoachAssigned: true,
      targetQuestionCount: 35,
      completedAt: '16:00',
    },
    {
      id: 'task-202',
      dayIndex: 0,
      subject: 'Kimya',
      topic: 'Modern Atom Teorisi — Orbitaller',
      durationMinutes: 60,
      status: 'completed',
      targetQuestionCount: 30,
      completedAt: '18:15',
    },
    {
      id: 'task-301',
      dayIndex: 2,
      subject: 'Geometri',
      topic: 'Üçgende Açılar ve Kenar Bağıntıları',
      durationMinutes: 80,
      status: 'completed',
      isCoachAssigned: true,
      targetQuestionCount: 40,
      completedAt: '14:30',
    },
    {
      id: 'task-401',
      dayIndex: 3,
      subject: 'Biyoloji',
      topic: 'Canlıların Ortak Özellikleri & Enzimler',
      durationMinutes: 60,
      status: 'pending',
      targetQuestionCount: 35,
    },
  ],
  subjectProgress: [
    { subject: 'Matematik', completedTasks: 6, totalTasks: 8, completedHours: 9.5, colorClass: 'bg-primary-500' },
    { subject: 'Fizik', completedTasks: 4, totalTasks: 5, completedHours: 5.5, colorClass: 'bg-attention' },
    { subject: 'Türkçe', completedTasks: 4, totalTasks: 5, completedHours: 4.0, colorClass: 'bg-success' },
    { subject: 'Kimya', completedTasks: 2, totalTasks: 4, completedHours: 3.0, colorClass: 'bg-warning' },
    { subject: 'Biyoloji', completedTasks: 2, totalTasks: 3, completedHours: 2.5, colorClass: 'bg-danger' },
  ],
};
