import { CoachDashboardViewModel } from './types';

export const initialCoachDashboardData: CoachDashboardViewModel = {
  coachName: 'Hasan Yılmaz',
  dateStr: '1 Eylül 2026 Salı',
  portfolioSummary: {
    planAdherenceAvg: 82,
    weeklyStudyHoursAvg: 19.4,
    activeStudentsCount: 24,
    attentionRequiredCount: 3,
  },
  attentionStudents: [
    {
      id: 'att-1',
      studentId: 'student-3',
      name: 'Zeynep Demir',
      grade: '12. Sınıf',
      field: 'Sayısal',
      severity: 'danger',
      issue: '5 gündür platforma giriş yapmadı. TYT Matematik planı %34 geride.',
      lastSeen: '5 gün önce',
      ctaLabel: 'Planı İncele',
      targetTab: 'plan',
    },
    {
      id: 'att-2',
      studentId: 'student-8',
      name: 'Emre Türk',
      grade: '11. Sınıf',
      field: 'Sözel',
      severity: 'danger',
      issue: 'Son AYT denemesinde Edebiyat neti beklenenden 8 net düşük çıktı.',
      lastSeen: '8 gün önce',
      ctaLabel: 'Denemeyi Gör',
      targetTab: 'exams',
    },
    {
      id: 'att-3',
      studentId: 'student-4',
      name: 'Ali Çelik',
      grade: '11. Sınıf',
      field: 'Eşit Ağırlık',
      severity: 'warning',
      issue: 'Haftalık geometri çalışma hedefini tamamlamadı (2/5 görev).',
      lastSeen: 'Dün',
      ctaLabel: 'Not Ekle',
      targetTab: 'notes',
    },
  ],
  todaySessions: [
    {
      id: 'sess-1',
      studentId: 'student-1',
      studentName: 'Ayşe Kaya',
      initials: 'AK',
      grade: '11. Sınıf',
      type: 'Haftalık Plan Değerlendirmesi',
      time: '14:30',
      duration: '30 dk',
      status: 'upcoming',
    },
    {
      id: 'sess-2',
      studentId: 'student-4',
      studentName: 'Ali Çelik',
      initials: 'AÇ',
      grade: '11. Sınıf',
      type: 'Geometri Hedef Belirleme',
      time: '16:00',
      duration: '45 dk',
      status: 'upcoming',
    },
    {
      id: 'sess-3',
      studentId: 'student-3',
      studentName: 'Zeynep Demir',
      initials: 'ZD',
      grade: '12. Sınıf',
      type: 'Motivasyon & Devamsızlık Takibi',
      time: '17:15',
      duration: '30 dk',
      status: 'upcoming',
    },
  ],
  pendingActions: [
    {
      id: 'act-1',
      studentId: 'student-1',
      studentName: 'Ayşe Kaya',
      type: 'Özdebir Deneme Analiz Onayı',
      time: '10 dk önce',
      urgent: true,
    },
    {
      id: 'act-2',
      studentId: 'student-3',
      studentName: 'Zeynep Demir',
      type: 'Haftalık Plan Revizyon Talebi',
      time: '2 saat önce',
      urgent: true,
    },
    {
      id: 'act-3',
      studentId: 'student-8',
      studentName: 'Emre Türk',
      type: 'Edebiyat Soru Listesi Talebi',
      time: 'Dün',
      urgent: false,
    },
  ],
};
