import { TeacherContentViewModel } from './types';

export const initialTeacherContentData: TeacherContentViewModel = {
  materials: [
    {
      id: 'mat-1',
      title: '11. Sınıf Limit ve Süreklilik Konu Fasikülü & Örnek Çözümler',
      subject: 'Matematik',
      topic: 'Limit ve Süreklilik',
      grade: '11. Sınıf',
      type: 'fasikul',
      pageCount: 32,
      assignedClassesCount: 2,
    },
    {
      id: 'mat-2',
      title: 'Limit 0/0 Belirsizliği ve Sadeleştirme Odak Testi',
      subject: 'Matematik',
      topic: 'Limit ve Süreklilik',
      grade: '11. Sınıf',
      type: 'test',
      questionCount: 24,
      durationMinutes: 40,
      assignedClassesCount: 1,
    },
    {
      id: 'mat-3',
      title: 'AYT Trigonometri Çıkmış Sorular & Özgün Deneme Testi',
      subject: 'Matematik',
      topic: 'Trigonometri',
      grade: '11. / 12. Sınıf',
      type: 'soru_bankasi',
      questionCount: 45,
      durationMinutes: 70,
      assignedClassesCount: 3,
    },
    {
      id: 'fiz-1',
      title: 'Optik & Işıkta Kırılma ve Prizmalar Detaylı Konu Anlatımı',
      subject: 'Fizik',
      topic: 'Optik',
      grade: '10. / 11. Sınıf',
      type: 'fasikul',
      pageCount: 28,
      assignedClassesCount: 2,
    },
    {
      id: 'fiz-2',
      title: 'Vektörler ve İki Boyutta Kuvvet Dengesi Tarama Testi',
      subject: 'Fizik',
      topic: 'Vektörler',
      grade: '11. Sınıf',
      type: 'test',
      questionCount: 20,
      durationMinutes: 35,
      assignedClassesCount: 2,
    },
  ],
};
