import { CoachStudentsViewModel } from './types';

export const initialCoachStudentsData: CoachStudentsViewModel = {
  students: [
    {
      id: 'student-1',
      name: 'Ayşe Kaya',
      initials: 'AK',
      grade: '11. Sınıf',
      field: 'Sayısal',
      exam: 'AYT',
      status: 'takipte',
      planAdherence: 91,
      weeklyStudyHours: 24.5,
      lastActivity: 'Bugün (10:30)',
      privateNotes: [
        {
          id: 'pnote-1',
          createdAt: '28 Ağustos 2026',
          category: 'Akademik',
          content: 'Fizik Optik konusunda soru çözüm hızını artırmamız gerekiyor. Haftalık plana 2 ek etüt ekledim.',
        },
        {
          id: 'pnote-2',
          createdAt: '15 Ağustos 2026',
          category: 'Veli Görüşmesi',
          content: 'Annesi Fatma Hanım ile görüşüldü. Evdeki çalışma ortamı ve motivasyonu oldukça iyi.',
        },
      ],
      weeklyPlanTasks: [
        {
          id: 'pt-1',
          dayName: 'Salı',
          subject: 'Matematik',
          topic: 'Limit ve Süreklilik',
          durationMinutes: 90,
          status: 'completed',
          isCoachAssigned: true,
          coachNote: 'Önceki denemedeki limit sorularının analizine dikkat et.',
        },
        {
          id: 'pt-2',
          dayName: 'Salı',
          subject: 'TYT Analizi',
          topic: 'Kasım Denemesi Çözümleri',
          durationMinutes: 45,
          status: 'in_progress',
          isCoachAssigned: true,
          coachNote: 'Yapamadığın 3 geometri sorusunu kesip defterine yapıştır.',
        },
        {
          id: 'pt-3',
          dayName: 'Çarşamba',
          subject: 'Geometri',
          topic: 'Üçgende Açılar ve Kenar Bağıntıları',
          durationMinutes: 80,
          status: 'pending',
          isCoachAssigned: true,
        },
        {
          id: 'pt-4',
          dayName: 'Perşembe',
          subject: 'Fizik',
          topic: 'Optik & Kırılma Tekrarı',
          durationMinutes: 60,
          status: 'pending',
          isCoachAssigned: true,
        },
      ],
      recentExams: [
        {
          id: 'ex-1',
          title: 'Özdebir Türkiye Geneli TYT-1',
          type: 'TYT',
          date: '28 Ağustos 2026',
          totalNet: 101.0,
          netChange: 4.25,
          subjectsSummary: 'Mat: 33.25 | Tr: 35.00 | Fen: 16.50 | Sos: 16.25',
          weakTopics: ['Optik & Kırılma', 'Mol Kavramı'],
        },
        {
          id: 'ex-2',
          title: 'Töder Kurumsal AYT Denemesi-1',
          type: 'AYT',
          date: '21 Ağustos 2026',
          totalNet: 64.5,
          netChange: 2.75,
          subjectsSummary: 'Mat: 32.25 | Fiz: 10.50 | Kim: 11.75 | Biy: 10.00',
          weakTopics: ['Limit & Süreklilik', 'İki Boyutta Hareket'],
        },
      ],
    },
    {
      id: 'student-3',
      name: 'Zeynep Demir',
      initials: 'ZD',
      grade: '12. Sınıf',
      field: 'Sayısal',
      exam: 'AYT',
      status: 'kritik',
      planAdherence: 34,
      weeklyStudyHours: 8.0,
      lastActivity: '5 gün önce',
      privateNotes: [
        {
          id: 'pnote-3',
          createdAt: '30 Ağustos 2026',
          category: 'Motivasyon',
          content: 'Devamsızlık ve ödev aksaması var. Bugünkü görüşmede çalışma programını hafifleterek yeniden başlatacağız.',
        },
      ],
      weeklyPlanTasks: [
        {
          id: 'pt-10',
          dayName: 'Pazartesi',
          subject: 'Matematik',
          topic: 'Türev Alma Kuralları',
          durationMinutes: 90,
          status: 'pending',
          isCoachAssigned: true,
        },
      ],
      recentExams: [
        {
          id: 'ex-3',
          title: 'Bilim Akademi Deneme-2',
          type: 'TYT',
          date: '18 Ağustos 2026',
          totalNet: 68.0,
          netChange: -5.5,
          subjectsSummary: 'Mat: 18.00 | Tr: 28.50 | Fen: 11.00 | Sos: 10.50',
          weakTopics: ['Problemler', 'Elektrik Akımı', 'Fonksiyonlar'],
        },
      ],
    },
    {
      id: 'student-4',
      name: 'Ali Çelik',
      initials: 'AÇ',
      grade: '11. Sınıf',
      field: 'Eşit Ağırlık',
      exam: 'AYT',
      status: 'dikkat',
      planAdherence: 58,
      weeklyStudyHours: 14.0,
      lastActivity: 'Dün',
      privateNotes: [
        {
          id: 'pnote-4',
          createdAt: '25 Ağustos 2026',
          category: 'Akademik',
          content: 'Geometriye karşı önyargısı var, üçgenler fasikülü bitirildikten sonra deneme netleri toparlanacaktır.',
        },
      ],
      weeklyPlanTasks: [],
      recentExams: [
        {
          id: 'ex-4',
          title: 'Özdebir TYT-1',
          type: 'TYT',
          date: '28 Ağustos 2026',
          totalNet: 78.5,
          netChange: 1.0,
          subjectsSummary: 'Mat: 22.00 | Tr: 34.00 | Sos: 17.50 | Fen: 5.00',
          weakTopics: ['Üçgende Açılar', 'Geometrik Kavramlar'],
        },
      ],
    },
    {
      id: 'student-8',
      name: 'Emre Türk',
      initials: 'ET',
      grade: '11. Sınıf',
      field: 'Sözel',
      exam: 'AYT',
      status: 'kritik',
      planAdherence: 21,
      weeklyStudyHours: 6.5,
      lastActivity: '8 gün önce',
      privateNotes: [],
      weeklyPlanTasks: [],
      recentExams: [],
    },
    {
      id: 'student-9',
      name: 'Nur Aydın',
      initials: 'NA',
      grade: '10. Sınıf',
      field: 'Eşit Ağırlık',
      exam: 'TYT',
      status: 'takipte',
      planAdherence: 73,
      weeklyStudyHours: 18.0,
      lastActivity: 'Dün',
      privateNotes: [],
      weeklyPlanTasks: [],
      recentExams: [],
    },
  ],
};
